(function(w){'use strict';var L=w.LegacyDisplay,last=0,running=false,timer=null,dashboard=null;
function state(ok,text){var e=document.getElementById('connection-state');L.setText(e,text);document.body.className=document.body.className.replace(/\s?is-offline/g,'').replace(/\s?is-online/g,'')+(ok?' is-online':' is-offline');}
function build(d){var box=document.getElementById('dashboard'),i,it,t,h,v;box.innerHTML='';dashboard=d;for(i=0;i<d.items.length;i++){it=d.items[i];t=document.createElement('section');t.className='tile '+(it.size||'medium');t.setAttribute('data-id',it.id);h=document.createElement('div');h.className='header';h.innerHTML='<span class="label"></span><span class="unit"></span>';v=document.createElement('div');v.className='value';v.setAttribute('data-path',it.path||'');v.setAttribute('data-role',it.role||'generic');v.setAttribute('data-formatter',it.formatter||'number');v.setAttribute('data-decimals',String(it.decimals));v.setAttribute('data-max-chars',String(it.maxChars||6));L.setText(h.getElementsByClassName('label')[0],it.label||it.path);L.setText(h.getElementsByClassName('unit')[0],it.unit||'');L.setText(v,'--');t.appendChild(h);t.appendChild(v);box.appendChild(t);}setTimeout(scaleAll,20);}
function scaleAll(){var es=document.getElementsByClassName('value'),i;for(i=0;i<es.length;i++)L.scale(es[i],es[i].getAttribute('data-max-chars'));}
function update(data){var es=document.getElementsByClassName('value'),i,e,path,raw,role,depth=false,item;for(i=0;i<es.length;i++){e=es[i];path=e.getAttribute('data-path');role=e.getAttribute('data-role');raw=L.get(data,path);item={formatter:e.getAttribute('data-formatter'),decimals:e.getAttribute('data-decimals')};if(role==='depth'&&raw!==null)depth=true;L.setText(e,L.format(raw,item));}last=L.now();if(document.body.getAttribute('data-page')==='anchor'&&!depth)state(true,'KEINE TIEFENDATEN');else state(true,'DATEN AKTUELL');}
function poll(){if(running)return;running=true;L.loadData(function(err,data){running=false;if(err){if(L.now()-last>3000)state(false,'KEINE VERBINDUNG');return;}update(data);});}
function start(config){var page=document.body.getAttribute('data-page'),d=config&&config.dashboards?config.dashboards[page]:null;if(!d)return;build(d);poll();timer=setInterval(poll,Math.max(250,parseInt(d.updateInterval,10)||1000));setInterval(function(){if(L.now()-last>3000)state(false,'KEINE VERBINDUNG');},1000);}
function init(){L.Storage.detect(function(){L.Storage.loadConfig(start);});}
if(w.addEventListener)w.addEventListener('resize',scaleAll,false);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,false);else init();
})(window);
